---
name:                   "Collection deployment"

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on:            ubuntu-latest
    steps:
    - name:             "Init: Run checkout@v2"
      uses:             actions/checkout@v2
    - name:             "Init: Get the version from the tag"
      run:              echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//
    - name:             "Ansible: deploy collection in galaxy"
      uses:             artis3n/ansible_galaxy_collection@v2
      with:
        api_key:        ${{ secrets.GALAXY_API_KEY }}
        galaxy_version: ${{ env.RELEASE_VERSION }}
